name: "Setup DBT Fusion Environment"
description: "Set up DBT Fusion environment for the given DBT Fusion version"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.12"
  uv-version:
    description: "uv version to use"
    required: true
    default: "0.8.22"
  dbtf-version:
    description: "DBT Fusion version to use"
    required: true
    default: "2.0.0-preview.33"

runs:
  using: "composite"
  steps:
    - name: Set up the environment
      uses: ./.github/actions/setup-python-env
      with:
        python-version: ${{ inputs.python-version }}
        uv-version: ${{ inputs.uv-version }}

    - name: Install DBT Fusion
      run: curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update --version ${{ inputs.dbtf-version }}
      shell: bash
    
    - name: add dbtf symlink
      run: ln -sf /home/runner/.local/bin/dbt /home/runner/.local/bin/dbtf
      shell: bash
