repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: "v2.0.8"
    hooks:
      - id: check-model-has-description
        files: ^models/
      - id: check-model-has-tests-by-group
        files: ^models/
        args:
          - "--tests"
          - "unique"
          - "unique_combination_of_columns"
          - "expect_compound_columns_to_be_unique"
          - "--test-cnt"
          - "1"
          - "--"
      - id: check-model-columns-have-desc
        files: ^models/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude: ^.devcontainer/devcontainer.json
      - id: pretty-format-json
        exclude: ^.devcontainer/devcontainer.json
        args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.7"
    hooks:
      - id: ruff-check
        args: [ --exit-non-zero-on-fix ]
      - id: ruff-format
