name: "{{cookiecutter.project_name}}"

profile: "{{cookiecutter.project_name}}"

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  {{cookiecutter.project_name}}:
    +schema: raw

models:
  {{cookiecutter.project_name}}:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
